# Datenstrom Yellow extension settings

Extension: Contact
Version: 1.0.3
Description: Contact form for sending emails.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-contact/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-contact
DocumentationLanguage: en, de, sv
Published: 2026-10-04 23:30:47
Status: maintained
system/workers/contact.php: contact.php, create, update
system/layouts/contact.html: contact.html, create, update, careful
content/contact/page.md: page.md, create, optional
